### ISSUE TITLE
Launching .app version is slow in macOS Mojave

### ISSUE THREAD

**Issue by aganders3** [gpilab/framework#14]
Launching the .app version of GPI takes about 30s in macOS Mojave for some reason.

It is slow when launching form the icon, or when using `open GPI.app` from the command line. It is *not* slow when calling the launch scripts directly in the app bundle. Updating GPI (via conda) in the app bundle does not seem to help.

I think this may have something to do with TCC, but I am not sure. Looking at the console `tccd` seems to be searching through many (all?) the files in the app bundle, which would explain it. I don't know how to prevent this. Maybe something in the Info.plist?

**Comment by aganders3** [comment]
I did a little more testing today in my Mojave VM and it seems this is solved if the code is signed with a Mac App Distribution certificate. This feels like more of a workaround than a fix to me, but ultimately if we want to distribute this code then maybe signing it is The Right Thing To Do.

I don't have enough experience with the Apple developer program to know how it works with a team of developers, but I can look into it. I'm not sure I should be signing this with a personal developer certificate (and if not I don't want my account revoked). Likewise if we do get to the point of automatically packaging a .app bundle we would need a way to put the certificate on the build server for signing.

Of course the other workaround is to only distribute via package managers. If that's the case we could still distribute some kind of .app (maybe an Automator App?) to launch GPI, but we lose some of the niceties like the dock icon, etc.

References:
* https://github.com/macvim-dev/macvim/issues/763
* https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing

**Comment by aganders3** [comment]
One more thing to explore (writing here so I don't forget): does the certificate become invalidated if GPI or any packages in the miniconda distribution inside the app are changed? This would happen for example if you ran `conda update` from inside the bundle.

**Comment by borupdaniel** [comment]
Closing, I am no longer supporting the .app launch option for now.
