### ISSUE TITLE
errors on starting GPI - residual root ownership?

### ISSUE THREAD

**Issue by pefs44** [gpilab/framework#2]
starting GPI, although the canvas and menu bar open, I get messages: 

Thu May  5 08:28:50 2016 - gpi.loader:121 - ERROR - Traceback (most recent call last):
  File "/Users/paul/gpi_stack/lib/python3.5/site-packages/gpi/loader.py", line 118, in loadMod
    py_compile.compile(fullpath, doraise=True)
  File "/Users/paul/gpi_stack/lib/python3.5/py_compile.py", line 143, in compile
    importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)
  File "<frozen importlib._bootstrap_external>", line 106, in _write_atomic
PermissionError: [Errno 13] Permission denied: '/Users/paul/gpi_stack/lib/python3.5/site-packages/gpi/types/__pycache__/globjectlist_GPITYPE.cpython-35.pyc.4644736656'

FAILED:/Users/paul/gpi_stack/lib/python3.5/site-packages/gpi/types/globjectlist_GPITYPE.py
Thu May  5 08:28:50 2016 - gpi.loader:121 - ERROR - Traceback (most recent call last):
  File "/Users/paul/gpi_stack/lib/python3.5/site-packages/gpi/loader.py", line 118, in loadMod
    py_compile.compile(fullpath, doraise=True)
  File "/Users/paul/gpi_stack/lib/python3.5/py_compile.py", line 143, in compile
    importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)
  File "<frozen importlib._bootstrap_external>", line 106, in _write_atomic
PermissionError: [Errno 13] Permission denied: '/Users/paul/gpi_stack/lib/python3.5/site-packages/gpi/types/__pycache__/numpy_GPITYPE.cpython-35.pyc.4638085320'

FAILED:/Users/paul/gpi_stack/lib/python3.5/site-packages/gpi/types/numpy_GPITYPE.py
Thu May  5 08:28:50 2016 - gpi.loader:121 - ERROR - Traceback (most recent call last):
  File "/Users/paul/gpi_stack/lib/python3.5/site-packages/gpi/loader.py", line 118, in loadMod
    py_compile.compile(fullpath, doraise=True)
  File "/Users/paul/gpi_stack/lib/python3.5/py_compile.py", line 143, in compile
    importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)
  File "<frozen importlib._bootstrap_external>", line 106, in _write_atomic
PermissionError: [Errno 13] Permission denied: '/Users/paul/gpi_stack/lib/python3.5/site-packages/gpi/types/__pycache__/python_GPITYPE.cpython-35.pyc.4638086232'

FAILED:/Users/paul/gpi_stack/lib/python3.5/site-packages/gpi/types/python_GPITYPE.py

ls -l shows:
drwxr-xr-x  5 root  admin    170 May  4 23:19 __pycache__
its contents are also owned by root.

chowning __pycache__ but not its contents, the error messages are eliminated.

something to check in the distributed versions?

Paul

**Comment by aganders3** [comment]
Sorry for missing this issue - it must have slipped past while @nckz and I were at (or preparing for) ISMRM.

Can you check the ownership of your `gpi_stack` directory? What about the `/Users/paul/gpi_stack/lib/python3.5/site-packages/gpi/` directory?

The only way I can think this might happen is if you installed GPI as root (or using `sudo`) or at some point ran GPI as root (or using `sudo`) or both.

**Comment by pefs44** [comment]
Hi 
in /Users/pauldrwxr-xr-x   18 paul  staff    612 May  3 00:52 gpi_stack
in /Users/paul/gpi_stack/lib/python3.5/site-packages















drwxr-xr-x  52 paul  staff    1768 May  3 00:52 gpi
running as root or sudo almost certainly not. slipping in a command-line sudo during install might have happened - but I don't remember doing so. 
Paul

Date: Thu, 2 Jun 2016 14:20:44 -0700

**Comment by pefs44** [comment]
Hi Ashley,


    I didn't figure out what was happening with the ownership, but things seemed to be working after a certain point, then vacation and

haven't managed to touch things again [☹]


Paul


________________________________
