### ISSUE TITLE
Looking ahead: bug with qt5.12

### ISSUE THREAD

**Issue by borupdaniel** [gpilab/framework#26]
Eric B. showed me a bug yesterday on his install, which uses MacPorts and is running qt5.12. In this bug, opening the node widget menu, closing it, and re-opening it causes nothing to show up unless clicked/selected — it appears as a blank window, the correct size, but with nothing in it. Clicking around will cause things to pop up again within the window. The same is also true for the node menu on a right click.

We're only supporting qt5.9 at the moment, but wanted to put this here in case someone's able to take a look at what's going on as we'll run into this bug eventually on some upgrade and it's not covered by our current tests, which don't involve the GUI.

**Comment by aganders3** [comment]
Qt 5.12 is also the next LTS release, so I agree it would be good to address this bug.

**Comment by aganders3** [comment]
Possibly related bugs:
https://bugreports.qt.io/browse/QTBUG-72387
https://bugreports.qt.io/browse/QTBUG-71988

**Comment by borupdaniel** [comment]
It seems like this may be caused by the bug described below:

https://codereview.qt-project.org/c/qt/qtbase/+/267755

Not sure if that means it's fixed as of a later Qt 5.12 version? If so we can probably close this — if not I'll leave it open for now.

**Comment by borupdaniel** [comment]
This appears to be fixed based on the latest qt 5.12, closing.
