### ISSUE TITLE
libpng issue after install

### ISSUE THREAD

**Issue by esbn** [gpilab/framework#3]
Hi there, 

I have just installed GIP on my macbook (OS: El Capitan) using ./GPI_Install_Latest-rc.sh ~/gpi_stack.

When I attempt to open GIP I get the following console output:

> esbenplenge$ /Users/esbenplenge/gpi_stack/bin/gpi

> GPI 1.0.0 (2015-11-13)  Copyright (C) 2014 Dignity Health
> This program comes with ABSOLUTELY NO WARRANTY; see the LICENSE for details.
> 
>     NO CLINICAL USE.  THE SOFTWARE IS NOT INTENDED FOR COMMERCIAL PURPOSES
> AND SHOULD BE USED ONLY FOR NON-COMMERCIAL RESEARCH PURPOSES.  THE SOFTWARE
> MAY NOT IN ANY EVENT BE USED FOR ANY CLINICAL OR DIAGNOSTIC PURPOSES.  YOU
> ACKNOWLEDGE AND AGREE THAT THE SOFTWARE IS NOT INTENDED FOR USE IN ANY HIGH
> RISK OR STRICT LIABILITY ACTIVITY, INCLUDING BUT NOT LIMITED TO LIFE SUPPORT
> OR EMERGENCY MEDICAL OPERATIONS OR USES.  LICENSOR MAKES NO WARRANTY AND HAS NOR LIABILITY ARISING FROM ANY USE OF THE SOFTWARE IN ANY HIGH RISK OR STRICT
> LIABILITY ACTIVITIES.
> 
> Traceback (most recent call last):
>   File "/Users/esbenplenge/gpi_stack/bin/gpi_launch", line 38, in <module>
>     from gpi import launch
>   File "/Users/esbenplenge/gpi_stack/lib/python3.5/site-packages/gpi/__init__.py", line 69, in <module>
>     QtGui = qtapi.import_module("QtGui")
>   File "/Users/esbenplenge/gpi_stack/lib/python3.5/site-packages/gpi/qtapi.py", line 48, in import_module
>     p = __import__('PyQt4', globals(), locals(), [moduleName], 0)
> ImportError: dlopen(/Users/esbenplenge/gpi_stack/lib/python3.5/site-packages/PyQt4/QtGui.so, 2): Library not loaded: @rpath/libpng16.16.dylib
>   Referenced from: /Users/esbenplenge/gpi_stack/lib/libQtGui.4.8.7.dylib
>   Reason: Incompatible library version: libQtGui.4.dylib requires version 39.0.0 or later, but libpng16.16.dylib provides version 34.0.0

I did a re-installation of pnglib, which did not change anything. Should I also re-install GIP, and if so, how do I do that? Any other suggestions to overcome this error?

Best regards,
Esben

**Comment by nckz** [comment]
Hi Esben,

I see the same issue.  It looks like the latest `pyqt` package might not be compiled with the correct version of `libpng` (similar to this past Anaconda problem https://groups.google.com/a/continuum.io/forum/#!topic/conda/vTn7xNkCkhM) it looks like reverting back to the last `pyqt` and `qt` builds works for me.  Try this:

```
/Users/esbenplenge/gpi_stack/bin/conda install pyqt=4.11.4=py35_1 qt=4.8.7=1
```

**Comment by nckz** [comment]
@aganders3 This doesn't seem to affect the Linux install.

**Comment by nckz** [comment]
I updated the `GPI_Install_Latest.sh` script so that it won't install the conflicting `qt` and `libpng` packages.  Its posted on https://github.com/gpilab/framework/releases

**Comment by esbn** [comment]
@nckz Thanks! 

> /Users/esbenplenge/gpi_stack/bin/conda install pyqt=4.11.4=py35_1 qt=4.8.7=1

did the trick.

**Comment by nckz** [comment]
Ok it seems that the following Anaconda packages are in conflict:
* pyqt 4.11.4 py35_3
* qt 4.8.7 3
* libpng 1.6.17 0

GPI v1.0.2 will require the 2nd build number for these packages so it is advisable not to upgrade these to the 3rd build.

I'm going to close this since we have a work around.
