### ISSUE TITLE
GPI on Windows : Error executing GPI nodes with C/C++ code

### ISSUE THREAD

**Issue by schudds** [gpilab/framework#4]
Even with a successful gpi_make, executing nodes with C/C++ code in GPI could lead to a failed state with the error as shown in the following image (error highlighted by yellow rectangular box): 
![fftw_fail](https://cloud.githubusercontent.com/assets/10438896/19494081/4487882e-9532-11e6-9e8b-d7043c7fa51b.PNG)

**Why do you see this ?**
This is most likely due to checking out precompiled code that used a different version of the C++ dependency/package when compiled initially, to the one that is installed in the Ubuntu shell. A quick check for this would to run the following command to identify the most recent version of GLIBCXX installed: 
$strings /home/user_acc_name/anaconda3/lib/python3.5/site-packages/../../libstdc++.so.6|grep GLIBCXX

**Comment by schudds** [comment]
**Solution**
If the most recent version installed does not match the required version specified in the error, a solution is to update the version by running the following command:
$conda install glibcc

Follow the instructions when prompted. On restarting GPI, the same node (FFTW in the example) should execute without throwing up an error.

**Comment by nckz** [comment]
It looks like we might have to package a Window-Linux or (Windows-Bash) version in the Anaconda cloud.

**Comment by borupdaniel** [comment]
Closing as this is >2 years old. Please feel free to re-open if relevant to current development!
