### ISSUE TITLE
Config>Generate User Library on Windows version crashes

### ISSUE THREAD

**Issue by MattWill660** [gpilab/framework#46]
Using Windows release, Clicking the generate user library button results in software crashing and closing itself.

Button showing empty parenthesis (usually, shows location that will be made)
![image](https://user-images.githubusercontent.com/41481302/75932152-ba068d00-5e44-11ea-98a9-4d6edc3b863a.png)

Error report
![image](https://user-images.githubusercontent.com/41481302/75932397-4f098600-5e45-11ea-9885-b56f76c4b08c.png)

**Comment by borupdaniel** [comment]
From the error message, it looks like GPI is supplying an empty `path` where it should be passing `/Users/<user>/gpi/<user>`. Shouldn't be too hard to figure out what's up with that.
