### ISSUE TITLE
GPI on Windows : Crash when loading 'matplotlib' node on canvas

### ISSUE THREAD

**Issue by schudds** [gpilab/framework#5]
When loading the matplotlib node on the canvas, GPI crashes (canvas disappears) with the following error:
OMP : Error #100: Fatal system error detected.
OMP: System error #22: Invalid argument
A screen shot of the error message has been attached : 
![gpi_crash_matplotlib_repeat](https://cloud.githubusercontent.com/assets/10438896/20206095/6a61f194-a79b-11e6-98ec-05c09f4c0f6d.PNG)

This seems to be associated with scipy (at least in this particular case). A quick way to test this was to recreate the same error by typing the following at command line : 
$ python -c 'import scipy; scipy.test()'

**Comment by schudds** [comment]
A working solution for this issue seems to be achieved by typing the following at command line before starting a session of GPI (At this point it is still unclear to me why) : 
$export KMP_AFFINITY=disabled

Now either instantiating matplotlib or runnign the scipy test command work without issues.

**Comment by nckz** [comment]
Does this still happen with the `nomkl` conda package installed?

**Comment by borupdaniel** [comment]
Closing as stale - please feel free to re-open if this is still an issue!
