### ISSUE TITLE
Lack of Firefox connectivity after Ubuntu installation and firefox execution

### ISSUE THREAD

**Issue by mnhoff** [gpilab/framework#6]
Hi

I install the Linux Bash shell, run it, install Xming X server and run it in the background, and the install and launch firefox.  THis goes fine, but firefox can't connect to the internet, despite my laptop being connected (firefox in Windows 10 connects just fine).

Did I miss something?

Mike

**Comment by schudds** [comment]
@mnhoff : It looks like the ubuntu package manager was able to install firefox. In that case you could try downloading the installer from command line, as a workaround.  
installer url : https://repo.continuum.io/archive/Anaconda3-4.3.1-Linux-x86_64.sh
Using wget , download the installer to the folder of your choice: 
`wget "https://repo.continuum.io/archive/Anaconda3-4.3.1-Linux-x86_64.sh" --header "Referer: repo.continuum.io"`

The wget command should show something like this:
![dload_anaconda_cmdline](https://cloud.githubusercontent.com/assets/10438896/24327759/5c36d262-118e-11e7-9072-24d8bc65b2d5.PNG)

You should be able to resume with the steps in the windows install documentation after the installer download step.

Sudarshan

**Comment by mnhoff** [comment]
Thanks Sudarshan...that got me further into the installation.  I am stumped at the GPI install, however.  When I type

conda install -c https://conda.anaconda.org/GPI gpi

I get the error

UnsatisfiableError: The following specifications were found to be in conflict:
  - gpi -> matplotlib 1.4.* -> dateutil -> python 2.6* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

I tried various commands, like

conda remove python 3.6*
conda remove openssl 1.0.1*
and
conda remove bottleneck

but each fails to resolve the error once I retype the install command.  The "conda remove bottleneck" command seems to do something, but it doesn't alleviate the problem.

**Comment by nckz** [comment]
@mnhoff - I think this is due to the anaconda package deps listed for GPI.  Try installing python 3.5 with:

```bash
$ conda install -c gpi python=3.5
```

**Comment by mnhoff** [comment]
Thanks Nick, that worked.  I'm now near the finish line, but got tripped again...  when I try to view the config via:
`gpi --config`
or if I launch gpi with:
```
export DISPLAY=:0
gpi
```
the following is output:
```
GPI 1.0.1 (2015-11-13)  Copyright (C) 2014 Dignity Health
This program comes with ABSOLUTELY NO WARRANTY; see the LICENSE for details.

    NO CLINICAL USE.  THE SOFTWARE IS NOT INTENDED FOR COMMERCIAL PURPOSES
AND SHOULD BE USED ONLY FOR NON-COMMERCIAL RESEARCH PURPOSES.  THE SOFTWARE
MAY NOT IN ANY EVENT BE USED FOR ANY CLINICAL OR DIAGNOSTIC PURPOSES.  YOU
ACKNOWLEDGE AND AGREE THAT THE SOFTWARE IS NOT INTENDED FOR USE IN ANY HIGH
RISK OR STRICT LIABILITY ACTIVITY, INCLUDING BUT NOT LIMITED TO LIFE SUPPORT
OR EMERGENCY MEDICAL OPERATIONS OR USES.  LICENSOR MAKES NO WARRANTY AND HAS
NOR LIABILITY ARISING FROM ANY USE OF THE SOFTWARE IN ANY HIGH RISK OR STRICT
LIABILITY ACTIVITIES.

Traceback (most recent call last):
  File "/home/mnhoff/anaconda3/bin/gpi_launch", line 38, in <module>
    from gpi import launch
  File "/home/mnhoff/anaconda3/lib/python3.5/site-packages/gpi/__init__.py", line 94, in <module>
    from .nodeAPI import *
  File "/home/mnhoff/anaconda3/lib/python3.5/site-packages/gpi/nodeAPI.py", line 40, in <module>
    from .dataproxy import DataProxy, ProxyType
  File "/home/mnhoff/anaconda3/lib/python3.5/site-packages/gpi/dataproxy.py", line 27, in <module>
    import numpy as np
  File "/home/mnhoff/anaconda3/lib/python3.5/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/home/mnhoff/anaconda3/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/mnhoff/anaconda3/lib/python3.5/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/mnhoff/anaconda3/lib/python3.5/site-packages/numpy/lib/polynomial.py", line 13, in <module>
    import numpy.core.numeric as NX
AttributeError: module 'numpy' has no attribute 'core'
```

**Comment by nckz** [comment]
Looks like the numpy core was added in version 1.3 (https://docs.scipy.org/doc/numpy/reference/c-api.coremath.html).  But I believe the deps call for 1.9.  Can you check your installed version by checking `numpy.__version__`?

**Comment by mnhoff** [comment]
It appears to be version: numpy: 1.9.3-py35_0

FYI, the command doesn't work, but I was able to determine the version this way:

```
mnhoff@RAD-30196702:~$ conda install -c https://conda.anaconda.org/GPI gpi
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/mnhoff/anaconda3:

The following NEW packages will be INSTALLED:

    nomkl: 1.0-0

The following packages will be UPDATED:

    gpi:   1.0.1-py35_0 GPI --> 1.0.2-py35_0       GPI
    numpy: 1.9.3-py35_0     --> 1.9.3-py35_nomkl_2     [nomkl]

Proceed ([y]/n)? n
```

**Comment by borupdaniel** [comment]
Closing as this is >2 years old. Please feel free to re-open if this is still an issue in any way!

**Comment by mnhoff** [comment]
no worries!  Resolved...
