### ISSUE TITLE
FreeSurfer 6.0 Library Conflict

### ISSUE THREAD

**Issue by nckz** [gpilab/framework#7]
We found installing Freesurfer 6.0 messes with some of the dynamic libraries and causes the GPI to abort, so we had to revert to Freesurfer 5.3 for the present. I’m sure there is a more elegant solution to get them to co-exist but as the changes in Freesurfer 6.0 have relatively little impact on what we use it for it was easier to revert to the previous version.

-Richard

**Comment by nckz** [comment]
My immediate inclination would be to install FreeSurfer in a conda environment e.g.:

```bash
$ conda create --name freesurfer python=3
```
This would allow you to add any package deps for FreeSurfer independently.  -everytime you’d like to use it, just make sure your in the environment.

```bash
source activate freesurfer
```

**Comment by nckz** [comment]
We’ll have to get more specific errors and python software versions, to tackle this.

**Comment by borupdaniel** [comment]
Closing as this is >2 years old and may not be relevant to newer versions of GPI.
