### ISSUE TITLE
Error when installing from GPI_Install_Latest.sh

### ISSUE THREAD

**Issue by justliketexas** [gpilab/framework#9]
There is a typo preventing installation from GPI_Install_Latest.sh.
`10:44 AM dallas@hank Downloads $ ./gpi_doesnt_work.sh ~/gpi_dummy
Installing the GPI stack for python 3.5 in /home/dallas/gpi_dummy ...
Downloading and Installing MiniConda...
--2017-06-30 10:44:27--  https://repo.continuum.io/miniconda//Miniconda3-latest-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.16.19.10, 104.16.18.10, 2400:cb00:2048:1::6810:120a, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.16.19.10|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-06-30 10:44:27 ERROR 404: Not Found.

chmod: cannot access 'Miniconda3-latest-Linux-x86_64.sh': No such file or directory
./gpi_doesnt_work.sh: line 120: ./Miniconda3-latest-Linux-x86_64.sh: No such file or directory
Installing the GPI packages...
./gpi_doesnt_work.sh: line 128: /home/dallas/gpi_dummy/bin/conda: No such file or directory
./gpi_doesnt_work.sh: line 129: /home/dallas/gpi_dummy/bin/conda: No such file or directory
./gpi_doesnt_work.sh: line 130: /home/dallas/gpi_dummy/bin/conda: No such file or directory
./gpi_doesnt_work.sh: line 135: /home/dallas/gpi_dummy/bin/conda: No such file or directory
Linking libgfortran.so.3 -> libgfortran.so.1...
ln: failed to create symbolic link '/home/dallas/gpi_dummy/lib/libgfortran.so.3': No such file or directory
Removing package files...
./gpi_doesnt_work.sh: line 145: /home/dallas/gpi_dummy/bin/conda: No such file or directory
Removing tmp files...
/home/dallas/Downloads
Done.
 
------------------------------------------------------------------------
To start GPI enter:
 
    $ /home/dallas/gpi_dummy/bin/gpi
 
To add GPI (and this Anaconda install) to your PATH, add the following
line to your .bashrc file:
 
PATH="/home/dallas/gpi_dummy/bin:$PATH"
10:44 AM dallas@hank Downloads $
`
The fix is on line 99:
MINICONDA_WEB=https://repo.continuum.io/miniconda/

needs to become
MINICONDA_WEB=https://repo.continuum.io/miniconda

Then everything works!

**Comment by aganders3** [comment]
This should be fixed in the current version of `GPI_INstall_Latest.sh` that is on the website and GitHub.
